/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EquipoRouteImport } from './routes/equipo'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ProyectoProject_codeRouteImport } from './routes/proyecto.$project_code'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipoRoute = EquipoRouteImport.update({
  id: '/equipo',
  path: '/equipo',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProyectoProject_codeRoute = ProyectoProject_codeRouteImport.update({
  id: '/proyecto/$project_code',
  path: '/proyecto/$project_code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/equipo': typeof EquipoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/proyecto/$project_code': typeof ProyectoProject_codeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/equipo': typeof EquipoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/proyecto/$project_code': typeof ProyectoProject_codeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/equipo': typeof EquipoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/proyecto/$project_code': typeof ProyectoProject_codeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/equipo' | '/sitemap.xml' | '/proyecto/$project_code'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/equipo' | '/sitemap.xml' | '/proyecto/$project_code'
  id: '__root__' | '/' | '/equipo' | '/sitemap.xml' | '/proyecto/$project_code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EquipoRoute: typeof EquipoRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ProyectoProject_codeRoute: typeof ProyectoProject_codeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipo': {
      id: '/equipo'
      path: '/equipo'
      fullPath: '/equipo'
      preLoaderRoute: typeof EquipoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proyecto/$project_code': {
      id: '/proyecto/$project_code'
      path: '/proyecto/$project_code'
      fullPath: '/proyecto/$project_code'
      preLoaderRoute: typeof ProyectoProject_codeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EquipoRoute: EquipoRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ProyectoProject_codeRoute: ProyectoProject_codeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
